"""Initial migration

Revision ID: eae91618c7ce
Revises: 
Create Date: 2024-04-17 23:25:03.999706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae91618c7ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('job_title')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
